# Generated by Django 4.1.4 on 2022-12-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Images',
        ),
    ]
